networks:
  default:
      name: DockerGraphQL

volumes:
  dbVol:
    driver: local

services:
  web:
    restart: always
    build: ./services
    working_dir: /services
    depends_on:
      - db
    expose:
      - "8000"
    links:
      - db:db
    volumes:
      - ./services:/usr/src/app
      - ./services/static:/usr/src/app/static
      - ./services:/services
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000 #/usr/local/bin/gunicorn services.wsgi:application -w 2 -b :8000 --reload

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbVol:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myDB

  nginx:
    restart: always
    build:
      context: ./nginx/
      dockerfile: dockerfile_nginx_dev
    ports:
      - "80:80"
    volumes:
      - ./services/static:/usr/src/app/static
    links:
      - web:web
