# Generated by Django 4.2.1 on 2023-05-27 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 26, 20, 46, 1, 482787)
            ),
        ),
    ]
