# Generated by Django 4.2.1 on 2023-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('occupancy_limit', models.IntegerField()),
                ('current_occupancy', models.IntegerField()),
                ('created_timestamp', models.DateTimeField()),
                ('last_updated_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='times',
        ),
        migrations.AddField(
            model_name='event',
            name='sessions',
            field=models.ManyToManyField(to='events.session'),
        ),
    ]
