# Generated by Django 4.2.1 on 2023-06-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_session_remove_event_times_event_sessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTime',
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Test', max_length=64),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='current_occupancy',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
